accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login_check, name='login'),
    path('logout/', logout, name='logout'),
    path('follow/', follow, name='follow'),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

from django.shortcuts import redirect


urlpatterns = [
    
    
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    
    path('post/', include('post.urls', namespace='post')),
    path('', lambda r: redirect('accounts:login'), name='root'),

    path('board/', include('board.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns

post/urls.py
from django.urls import path
from .views import *
from . import views

app_name = 'post'

urlpatterns = [
    
    path('', post_list, name='post_list'),
    path('new', post_new, name='post_new'),
    path('edit/<int:pk>/', post_edit, name='post_edit'),
    path('delete/<int:pk>/', post_delete, name='post_delete'),
    path('like', post_like, name='post_like'),
    path('bookmark', post_bookmark, name='post_bookmark'),
    path('comment/new', comment_new, name='comment_new'),
    path('comment_detail/new', comment_new_detail, name='comment_new_detail'),
    
   
    path('comment/delete', comment_delete, name='comment_delete'),
    path('explore/tags/<tag>/', post_list, name='post_search'),
    path('<int:pk>/', post_detail, name='post_detail'),
    
    
    path('<username>/list/detail', my_post_list, name='my_post_list'),

    
    path('<int:pk>/', views.post_detail, name='detail'),
    path('<int:pk>/', post_detail, name='post_detail'),
    path('posts/user/<str:username>/', views.user_post_list, name='user_post_list'),
]

post/models.py
from django.conf import settings
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
import re


def photo_path(instance, filename):
    from time import gmtime, strftime
    from random import choice
    import string
    arr = [choice(string.ascii_letters) for _ in range(8)]
    pid = ''.join(arr)
    extension = filename.split('.')[-1]
    return '{}/{}/{}.{}'.format(strftime('post/%Y/%m/%d/'), instance.author.username, pid, extension)


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    photo = ProcessedImageField(upload_to=photo_path,
                                processors=[ResizeToFill(600, 600)],
                                format='JPEG',
                                options={'quality': 90},
                                blank=True, null=True)
    content = models.CharField(max_length=140, help_text="최대 140자 입력 가능")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tag_set = models.ManyToManyField('Tag', blank=True)
    like_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='like_user_set',
                                           through='Like')  # post.like_set 으로 접근 가능
    bookmark_user_set = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                           blank=True,
                                           related_name='bookmark_user_set',
                                           through='Bookmark')  # post.like_set 으로 접근 가능
    
    
    

    class Meta:
        ordering = ['-created_at']

    # NOTE: content에서 tags를 추출하여, Tag 객체 가져오기, 신규 태그는 Tag instance 생성, 본인의 tag_set에 등록,
    def tag_save(self):
        tags = re.findall(r'#(\w+)\b', self.content)

        if not tags:
            return

        for t in tags:
            tag, tag_created = Tag.objects.get_or_create(name=t)
            self.tag_set.add(tag)  # NOTE: ManyToManyField 에 인스턴스 추가

    @property
    def like_count(self):
        return self.like_user_set.count()
    
    @property
    def bookmark_count(self):
        return self.bookmark_user_set.count()
    
    
    

    def __str__(self):
        return self.content


class Tag(models.Model):
    name = models.CharField(max_length=140, unique=True)

    def __str__(self):
        return self.name


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('user', 'post')
        )
        
class Bookmark(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = (
            ('user', 'post')
        )
        


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.content

post/forms.py
from django import forms
from .models import Comment, Post

class PostForm(forms.ModelForm):
    photo = forms.ImageField(label='', required=False)
    content = forms.CharField(label='', widget=forms.Textarea(attrs={
        'class': 'post-new-content',
        'rows': 5,
        'cols': 50,
        'placeholder': '140자 까지 등록 가능합니다'
    }))
    
    class Meta:
        model = Post
        fields = ['photo', 'content']
    
    
class CommentForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.TextInput(attrs={
        'class': 'comment-form',
        'size': '70px',
        'placeholder': '댓글 달기...',
        'maxlength': '40', }))
    
    class Meta:
        model = Comment
        fields = ['content']
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

post/views.py
import json
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.views.decorators.http import require_POST
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .forms import PostForm, CommentForm

from .models import Post, Like, Comment,Tag
from django.db.models import Count


def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comment_form = CommentForm()
    
    return render(request, 'post/post_detail.html', {
        'comment_form': comment_form,
        'post': post,
    })
    
@login_required
def my_post_list(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    user_profile = user.profile
    
    target_user = get_user_model().objects.filter(id=user.id).select_related('profile') \
        .prefetch_related('profile__follower_user__from_user', 'profile__follow_user__to_user')
        
    post_list = user.post_set.all()
    
    all_post_list = Post.objects.all()
    
    return render(request, 'post/my_post_list.html', {
        'user_profile': user_profile,
        'target_user': target_user,
        'post_list': post_list,
        'all_post_list': all_post_list,
        'username': username,
    })
    

def post_list(request, tag=None):
    tag_all = Tag.objects.annotate(num_post=Count('post')).order_by('-num_post')
    
    if tag:
        post_list = Post.objects.filter(tag_set__name__iexact=tag) \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                              'author__profile__follower_user', 'author__profile__follower_user__from_user') \
            .select_related('author__profile')
    else:
        post_list = Post.objects.all() \
            .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                              'author__profile__follower_user', 'author__profile__follower_user__from_user') \
            .select_related('author__profile')

    comment_form = CommentForm()
    
    paginator = Paginator(post_list, 5)  # 페이지네이션을 10개씩 설정
    page_num = request.GET.get('page', 1)
    
    try:
        posts = paginator.page(page_num)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    
    if request.method == 'POST':
        tag = request.POST.get('tag')
        tag_clean = ''.join(e for e in tag if e.isalnum())
        return redirect('post:post_search', tag_clean)
    
    if request.user.is_authenticated:
        username = request.user
        user = get_object_or_404(get_user_model(), username=username)
        user_profile = user.profile
        follow_set = request.user.profile.get_following
        follow_post_list = Post.objects.filter(author__profile__in=follow_set)
        
        return render(request, 'post/post_list.html', {
            'user_profile': user_profile,
            'tag': tag,
            'posts': posts,
            'follow_post_list': follow_post_list,
            'comment_form': comment_form,
            'tag_all': tag_all,
        })
    else:
        return render(request, 'post/post_list.html', {
            'tag': tag,
            'posts': posts,
            'comment_form': comment_form,
            'tag_all': tag_all,
        })
    

@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            post.tag_save()
            messages.info(request, '새 글이 등록되었습니다')
            return redirect('post:post_list')
    else:
        form = PostForm()
    return render(request, 'post/post_new.html', {
        'form': form,
    })



@login_required
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user:
        messages.warning(request, '잘못된 접근입니다')
        return redirect('post:post_list')
    
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            post.tag_set.clear()
            post.tag_save()
            messages.success(request, '수정완료')
            return redirect('post:post_list')
    else:
        form = PostForm(instance=post)
    return render(request, 'post/post_edit.html', {
        'post': post,
        'form': form,
    })

    
@login_required
@require_POST
def post_like(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_like, post_like_created = post.like_set.get_or_create(user=request.user)

    if not post_like_created:
        post_like.delete()
        message = "좋아요 취소"
    else:
        message = "좋아요"

    context = {'like_count': post.like_count,
               'message': message}

    return HttpResponse(json.dumps(context), content_type="application/json")


@login_required
@require_POST
def post_bookmark(request):
    pk = request.POST.get('pk', None)
    post = get_object_or_404(Post, pk=pk)
    post_bookmark, post_bookmark_created = post.bookmark_set.get_or_create(user=request.user)

    if not post_bookmark_created:
        post_bookmark.delete()
        message = "북마크 취소"
    else:
        message = "북마크"

    context = {'bookmark_count': post.bookmark_count,
               'message': message}

    return HttpResponse(json.dumps(context), content_type="application/json")    
    

@login_required
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.author != request.user or request.method == 'GET':
        messages.warning(request, '잘못된 접근입니다.')
        return redirect('post:post_list')

    if request.method == 'POST':
        post.delete()
        # messages.success(request, '삭제완료')
        return redirect('post:post_list')


@login_required
def comment_new(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return render(request, 'post/comment_new_ajax.html', {
                'comment': comment,   
            })
    return redirect("post:post_list")


@login_required
def comment_new_detail(request):
    pk = request.POST.get('pk')
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return render(request, 'post/comment_new_detail_ajax.html', {
                'comment': comment,
            })




















@login_required
def comment_delete(request):
    pk = request.POST.get('pk')
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == 'POST' and request.user == comment.author:
        comment.delete()
        message = '삭제완료'
        status = 1
    
    else:
        message = '잘못된 접근입니다'
        status = 0
        
    return HttpResponse(json.dumps({'message': message, 'status': status, }), content_type="application/json")





from django.shortcuts import render, get_object_or_404
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Post
from .forms import CommentForm
from django.contrib.auth.decorators import login_required

@login_required
def user_post_list(request, username):
    user = get_object_or_404(get_user_model(), username=username)
    post_list = Post.objects.filter(author=user) \
        .prefetch_related('tag_set', 'like_user_set__profile', 'comment_set__author__profile',
                          'author__profile__follower_user', 'author__profile__follower_user__from_user') \
        .select_related('author__profile')

    comment_form = CommentForm()
    
    return render(request, 'post/post_list.html', {
        'posts': post_list,
        'comment_form': comment_form,
        'user_profile': user.profile,
    })

post/templates/post/comment_new_ajax.html
<div class="comment-detail" id="comment{{ comment.id }}">
    
    <!-- <div class="comment"> -->
        <div class="nick_name m_text">{{ comment.author.profile.nickname }}</div>
        <div>{{ comment.content }}</div>
        
            {% if user == comment.author %}
            <input type="button" class="del-comment" data-name="comment_delete" value="삭제" name="{{ comment.id }}">
            {% endif %}
        
        <div class="time">{{ comment.created_at|timesince }}</div>
    <!-- </div> -->
</div>

post/templates/post/layout.html
{% extends "layout.html" %}

post/templates/post/post_ajax_detail.html
<script type="text/javascript">

(function(){
    const delegation = document.querySelector('.contents_box');
    
    function delegationFunc(e) {
        let elem = e.target;
        
        console.log(elem);
        
        while (!elem.getAttribute('data-name')){
            elem = elem.parentNode;
            
            if (elem.nodeName === 'BODY'){
                elem = null;
                return;
            }
        }
        
        if (elem.matches('[data-name="heartbeat"]')){
            console.log('하트!');

            var pk = elem.getAttribute('name');
            console.log(pk);

            $.ajax({
                type: "POST",
                url: "{% url 'post:post_like' %}",
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (response){
                    // alert('성공!');
                    var likeCount = document.querySelector('#like-count-'+pk);
                    console.log(likeCount)
                    likeCount.innerHTML = '좋아요' + response.like_count + '개';
                },
                error: function (request, status, error) {
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });
            
            
        }else if (elem.matches('[data-name="bookmark"]')){
            console.log("북마크");
            var pk = elem.getAttribute('name');
            console.log(pk);
            
            $.ajax({
                type: "POST",
                url: "{% url 'post:post_bookmark' %}",
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                dataType: "json",
                success: function (response){
                    // alert('성공!');
                    var bookmarkCount = document.querySelector('#bookmark-count-'+pk);
                    bookmarkCount.innerHTML = '북마크' + response.bookmark_count + '개';
                },
                error: function (request, status, error) {
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });
            
        }else if (elem.matches('[data-name="comment"]')){
            console.log('새댓글');
            var pk = elem.getAttribute('name');
            var content = document.querySelector('#add-comment-post'+pk+'>input[type=text]').value;
            console.log(pk);
            console.log(content);
            if(content.length > 140) {
                alert("댓글은 최대 140자 입력 가능합니다. 현재 글자수 :"+content.length);
                return;
            }
            $.ajax({
                type: "POST",
                url: "{% url 'post:comment_new_detail' %}",
                data: {
                    'pk': pk,
                    'content': content,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "html",
                success: function(data, textStatus, jqXHR){
                    console.log("성공!")
                    document.querySelector("#comment-list-ajax-post"+pk).insertAdjacentHTML("afterbegin", data);
                    
                },
                error: function(request, status, error){
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });
        }else if(elem.matches('[data-name="comment_delete"]')){
            var pk = elem.getAttribute('name');

            $.ajax({
                type: "POST",
                url: "{% url 'post:comment_delete' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "json",
                success: function(response){
                    if(response.status){
                        document.querySelector('#comment'+pk).remove();
                    }
                },
                error: function(request, status, error){
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                } 
            });
        }else if(elem.matches('[data-name="follow"]')){
            console.log("팔로우!");
            var pk = elem.getAttribute('name');
            
            $.ajax({
                type:"POST",
                url: "{% url 'accounts:follow' %}",
                data: {
                    'pk': pk,
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                },
                dataType: "json",
                success: function(response){
                    console.log("성공");
                    if(response.status){
                        document.querySelector('input.follow[name=\''+pk+'\']').value="팔로우 취소";
                    }else{
                        document.querySelector('input.follow[name=\''+pk+'\']').value="팔로우";
                    }
                },
                error: function(request, status, error){
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                }
            })
        }
        
        
        
        elem.classList.toggle('on');
    }
    
    
    delegation.addEventListener('click', delegationFunc);
})();

</script>

post/templates/post/post_edit.html
{% extends "post/layout.html" %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/new_post.css' %}">
{% endblock %}



{% block content %}
<div id="main_container">
    <div class="post_form_container">
        <form action="#" class="post_form" method="post" enctype="multipart/form-data">
            <div class="title">
                Edit Post
            </div>
            <div class="preview">
                <div class="upload">
                    <div class="post_btn">
                        {% if post %}
                            <p><img id="img_id" src="{{ post.photo.url }}" style="width: 300px; height: 300px; object-fit: cover" ></p>
                        {% endif %}
                    </div>
                </div>
            </div>
            
            {% csrf_token %}
            {{ form.as_p }}
            
            <input class="submit_btn" type="submit" value="수정완료">
        </form>
    </div>
</div>
<script>
    const photo = document.querySelector('#img_id');
    document.querySelector('#photo-clear_id').remove();
    document.querySelector("label[for='photo-clear_id']").remove();
    
    
    function upload_img(input) {
        var reader = new FileReader();
        if (input.files && input.files[0]){
            reader.onload = function (e) {
            photo.setAttribute('src',e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    let idPhoto = document.querySelector('#id_photo');
    
    idPhoto.addEventListener('change',function(){
        upload_img(this);
    });










</script>























{% endblock %}

post/templates/post/script_ajax.html
<script type="text/javascript">
    (function(){
        const delegation = document.querySelector('.contents_box');
        const side_box = document.querySelector('.side_box');
        const header = document.querySelector('#header');
        
        
        
        function delegationFunc(e) {
            let elem = e.target;
            
            console.log(elem);
            
            while (!elem.getAttribute('data-name')){
                elem = elem.parentNode;
                
                if (elem.nodeName === 'BODY'){
                    elem = null;
                    return;
                }
            }
            
            if (elem.matches('[data-name="heartbeat"]')){
                console.log('하트!');
    
                var pk = elem.getAttribute('name');
                console.log(pk);
    
                $.ajax({
                    type: "POST",
                    url: "{% url 'post:post_like' %}",
                    data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                    dataType: "json",
                    success: function (response){
                        // alert('성공!');
                        var likeCount = document.querySelector('#like-count-'+pk);
                        likeCount.innerHTML = '좋아요' + response.like_count + '개';
                    },
                    error: function (request, status, error) {
                        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                    },
                });
                
                
            }else if (elem.matches('[data-name="bookmark"]')){
                console.log('북마크!');
    
                var pk = elem.getAttribute('name');
                console.log(pk);
    
                $.ajax({
                    type: "POST",
                    url: "{% url 'post:post_bookmark' %}",
                    data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' },
                    dataType: "json",
                    success: function (response){
                        // alert('성공!');
                        var bookmarkCount = document.querySelector('#bookmark-count-'+pk);
                        bookmarkCount.innerHTML = '북마크' + response.bookmark_count + '개';
                    },
                    error: function (request, status, error) {
                        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                    },
                });
            }else if (elem.matches('[data-name="comment"]')){
                console.log('새댓글')
                var pk = elem.getAttribute('name');
                var content = document.querySelector('#add-comment-post'+pk+'>input[type=text]').value;
                console.log(content);
                
                if(content.length > 140) {
                    alert("댓글은 최대 140자 입력 가능합니다. 현재 글자수 :"+content.length);
                    return;
                }
                
                if(content.length == 0) {
                    alert("글자를 하나라도 넣어주세요. 현재 글자수 :"+content.length);
                    return;
                }
                
                
                $.ajax({
                    type: "POST",
                    url: "{% url 'post:comment_new' %}",
                    data: {
                        'pk': pk,
                        'content': content,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "html",
                    success: function(data, textStatus, jqXHR){
                        console.log("성공!")
                        document.querySelector("#comment-list-ajax-post"+pk).insertAdjacentHTML("afterbegin", data);
                        
                    },
                    error: function(request, status, error){
                        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                    },
                });
            }else if(elem.matches('[data-name="comment_delete"]')){
                var pk = elem.getAttribute('name');
    
                $.ajax({
                    type: "POST",
                    url: "{% url 'post:comment_delete' %}",
                    data: {
                        'pk': pk,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "json",
                    success: function(response){
                        if(response.status){
                            document.querySelector('#comment'+pk).remove();
                        }
                    },
                    error: function(request, status, error){
                        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                    } 
                });
            }else if(elem.matches('[data-name="follow"]')){
                console.log("팔로우!");
                var pk = elem.getAttribute('name');
                
                $.ajax({
                    type:"POST",
                    url: "{% url 'accounts:follow' %}",
                    data: {
                        'pk': pk,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    dataType: "json",
                    success: function(response){
                        console.log("성공");
                        if(response.status){
                            document.querySelector('input.follow[name=\''+pk+'\']').value="팔로우 취소";
                        }else{
                            document.querySelector('input.follow[name=\''+pk+'\']').value="팔로우";
                        }
                    },
                    error: function(request, status, error){
                        alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                    }
                })
            }
            elem.classList.toggle('on');
        }
        
        
        function resizefunc(){
            // console.log('리사이즈')
            if(pageYOffset >= 10){
                let calcWidth = (window.innerWidth * 0.5) + 167;
                if(side_box){
                    side_box.style.left = calcWidth + "px";
                }
            }
        }
        
        function scrollfunc(){
            var scrollHeight = pageYOffset + window.innerHeight;
            var documentHeight = document.body.scrollHeight;
            
            if (pageYOffset >= 10){
                header.classList.add('on');
                resizefunc();
                if(side_box){
                    side_box.classList.add('on');
                }
            } else {
                header.classList.remove('on');
                if(side_box){
                    side_box.classList.remove('on');
                    side_box.removeAttribute('style');
                }
            }
            
            if(scrollHeight >= documentHeight){
                var page = document.querySelector('#page').value;
                
                console.log(page);
                
                var end_page = {{ posts.paginator.num_pages }}
                if(page > end_page){
                    return;
                }
                document.querySelector('#page').value = parseInt(page) + 1;
                callMorePostAjax(page);
            }
        }
        
        function callMorePostAjax(page) {
            var end_page = {{ posts.paginator.num_pages }};
            
            
            
            if(page > end_page){
                return;
            }
            $.ajax({
                type: 'POST',
                url: "{% url 'post:post_list' %}",
                data: {
                    'page': page,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                dataType: 'html',
                success: addMorePostAjax,
                error: function(request, status, error){
                    alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                }
            });
        }
     
        function addMorePostAjax(data, textStatus, jqXHR) {
        let post = document.querySelector('#post_list_ajax');
            
            post.insertAdjacentHTML("beforeend", data);
            
            
        }
    
    
        window.addEventListener('resize', resizefunc);
        window.addEventListener('scroll', scrollfunc);
        delegation.addEventListener('click', delegationFunc);
    })();
    </script>